/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niksc
 */
public class GuiPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiPedido
     * @param pedido
     * @param pessoa
     * @param produto
     */
    public GuiPedido(ArrayList<Pedido> pedido, ArrayList<Pessoa> pessoa, ArrayList<Produto> produto) {
        initComponents();
        ped = pedido;
        pes = pessoa;
        prod = produto;
        modTblPedido = (DefaultTableModel) tblItemPedido.getModel();
        // Recebe todas as array do GuiMenu e armazena em variavel local
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDadosVendedor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCpfVendedor = new javax.swing.JButton();
        lblNomeVendedor = new javax.swing.JLabel();
        ftxCpfVendedor = new javax.swing.JFormattedTextField();
        pnPeido = new javax.swing.JPanel();
        btnNumPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxFormaPagto = new javax.swing.JComboBox<>();
        txtNumPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ftxDataPedido = new javax.swing.JFormattedTextField();
        pnItensPedido = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCodProd = new javax.swing.JButton();
        txtCodProd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtdeVendida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemPedido = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblValTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblQtdeItensPedidos = new javax.swing.JLabel();
        pnDadosClientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCpfCliente = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        ftxCpfCliente = new javax.swing.JFormattedTextField();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");

        pnDadosVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        jLabel5.setText("CPF Vendedor");

        btnCpfVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnCpfVendedor.setEnabled(false);
        btnCpfVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpfVendedorActionPerformed(evt);
            }
        });

        lblNomeVendedor.setText(" ");
        lblNomeVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        try {
            ftxCpfVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCpfVendedor.setEnabled(false);
        ftxCpfVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxCpfVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDadosVendedorLayout = new javax.swing.GroupLayout(pnDadosVendedor);
        pnDadosVendedor.setLayout(pnDadosVendedorLayout);
        pnDadosVendedorLayout.setHorizontalGroup(
            pnDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(ftxCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDadosVendedorLayout.setVerticalGroup(
            pnDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosVendedorLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCpfVendedor)
                    .addGroup(pnDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(ftxCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeVendedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPeido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        btnNumPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnNumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumPedidoActionPerformed(evt);
            }
        });

        jLabel1.setText("Número do Pedido");

        jLabel3.setText("Forma de Pagamento");

        cbxFormaPagto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Vista", "Parcelado" }));
        cbxFormaPagto.setEnabled(false);

        txtNumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data do Pedido");

        try {
            ftxDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxDataPedido.setEnabled(false);
        ftxDataPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxDataPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPeidoLayout = new javax.swing.GroupLayout(pnPeido);
        pnPeido.setLayout(pnPeidoLayout);
        pnPeidoLayout.setHorizontalGroup(
            pnPeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPeidoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftxDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPeidoLayout.setVerticalGroup(
            pnPeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPeidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNumPedido)
                    .addGroup(pnPeidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(cbxFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnItensPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        lblDescricao.setText(" ");
        lblDescricao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setText("Código do Produto");

        btnCodProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnCodProd.setEnabled(false);
        btnCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodProdActionPerformed(evt);
            }
        });

        txtCodProd.setEnabled(false);
        txtCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdActionPerformed(evt);
            }
        });

        jLabel7.setText("Qtde Vendida");

        txtQtdeVendida.setEnabled(false);

        tblItemPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit.", "Qtde. Vend.", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemPedido);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnRemover.setText("Remover Item");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnAdicionar.setText("Adicionar Item");
        btnAdicionar.setEnabled(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor Total do Pedido");

        lblValTotal.setText(" ");
        lblValTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setText("Qtde de Itens Pedidos");

        lblQtdeItensPedidos.setText(" ");
        lblQtdeItensPedidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout pnItensPedidoLayout = new javax.swing.GroupLayout(pnItensPedido);
        pnItensPedido.setLayout(pnItensPedidoLayout);
        pnItensPedidoLayout.setHorizontalGroup(
            pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnItensPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnItensPedidoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnItensPedidoLayout.createSequentialGroup()
                        .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnItensPedidoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemover)
                                .addGap(36, 36, 36))
                            .addGroup(pnItensPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdeVendida))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnItensPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQtdeItensPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(lblValTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnItensPedidoLayout.setVerticalGroup(
            pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnItensPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCodProd)
                    .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao)
                        .addComponent(jLabel7)
                        .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblValTotal))
                .addGap(18, 18, 18)
                .addGroup(pnItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblQtdeItensPedidos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDadosClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        jLabel4.setText("CPF Cliente");

        btnCpfCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnCpfCliente.setEnabled(false);
        btnCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpfClienteActionPerformed(evt);
            }
        });

        lblNomeCliente.setText(" ");
        lblNomeCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        try {
            ftxCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCpfCliente.setEnabled(false);
        ftxCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxCpfClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDadosClientesLayout = new javax.swing.GroupLayout(pnDadosClientes);
        pnDadosClientes.setLayout(pnDadosClientesLayout);
        pnDadosClientesLayout.setHorizontalGroup(
            pnDadosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDadosClientesLayout.setVerticalGroup(
            pnDadosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosClientesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnDadosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCpfCliente)
                    .addGroup(pnDadosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(ftxCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIncluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnDadosVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnItensPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnDadosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addGap(76, 76, 76))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(pnPeido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(pnDadosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDadosVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(pnPeido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(540, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxDataPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxDataPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxDataPedidoActionPerformed

    private void ftxCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxCpfClienteActionPerformed

    private void ftxCpfVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxCpfVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxCpfVendedorActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        
        if(tblItemPedido.getSelectedRow() == -1){
            
            JOptionPane.showMessageDialog(null, "Linha não selecionada", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else{
            
            for(int i = 0; i < prod.size(); i++){
                if(prod.get(i).getCodigo().equals(tblItemPedido.getValueAt(tblItemPedido.getSelectedRow(), 0))){
                    prodselect = prod.get(i);
                }
                
               
            }
           
            prodselect.setQtdeEstoque(prodselect.getQtdeEstoque() + Double.parseDouble((String) tblItemPedido.getValueAt(tblItemPedido.getSelectedRow(), 3)));
            subtotal = Double.parseDouble((String)tblItemPedido.getValueAt(tblItemPedido.getSelectedRow(), 4));
            
            pedenc.voltaCredito(subtotal);
            total -= subtotal;
            
            lblValTotal.setText(String.valueOf(total));
            modTblPedido.removeRow(tblItemPedido.getSelectedRow());
            lblQtdeItensPedidos.setText(String.valueOf(modTblPedido.getRowCount()));
            
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        for (int i = 0; i < pes.size(); i++){
            if(pes.get(i).getCpf().equals(ftxCpfCliente.getText().replaceAll("[\\.\\-]", ""))){
                clienc = (Cliente) pes.get(i);
            }
        }
        
        
        DecimalFormat df = new DecimalFormat("#.##");
        
        if(txtQtdeVendida.getText().equals("0") || txtQtdeVendida.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Dgite uma quantidade vendida valida", "Aviso", JOptionPane.ERROR_MESSAGE);
            
        }else if (Double.parseDouble(txtQtdeVendida.getText()) > prdenc.getQtdeEstoque()) {
                
            JOptionPane.showMessageDialog(null, "Quantidade em estoque insuficiente", "Aviso", JOptionPane.ERROR_MESSAGE);
            
            } else {
                
                objItemPedido = new ItemPedido(modTblPedido.getRowCount() + 1, Double.parseDouble(txtQtdeVendida.getText()), prdenc);
                                  //Codigo                Descrição               Prec Unit                                                 QtdeVend
                String linha[] = {txtCodProd.getText(), lblDescricao.getText(), String.valueOf(objItemPedido.getProduto().getPreco()), txtQtdeVendida.getText()};    
                
                subtotal = Double.parseDouble(txtQtdeVendida.getText()) * objItemPedido.getProduto().getPreco();
                if (clienc.getLimiteDisp() < subtotal) {
                    JOptionPane.showMessageDialog(null, "Limite insuficiente", "Aviso", JOptionPane.ERROR_MESSAGE);
                } else {
                    pedenc.addItem(objItemPedido);
                    modTblPedido.addRow(linha);
                    modTblPedido.setValueAt(df.format(subtotal), modTblPedido.getRowCount() - 1, 4);

                    total += subtotal;

                    lblValTotal.setText(String.valueOf(total));
                    lblQtdeItensPedidos.setText(String.valueOf(modTblPedido.getRowCount()));
                    
                    txtCodProd.setText(null);
                    lblDescricao.setText(" ");
                    txtQtdeVendida.setText("");
                    btnIncluir.setEnabled(true);
                    
                    btnAdicionar.setEnabled(false);
                }   
            }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        if(alterar){
            pedenc.setDataPagto(ftxDataPedido.getText().replaceAll("/", ""));
            if(cbxFormaPagto.getSelectedIndex() == 0){
                pedenc.setFormaPagto(true);
            }else{
                pedenc.setFormaPagto(false);
            }
            
            ped.add(pedenc);
        }else{
            ped.add(pedenc);
        }
        
        btnIncluir.setEnabled(false);
        txtCodProd.setEnabled(false);
        btnCodProd.setEnabled(false);
        tblItemPedido.setEnabled(false);
        btnRemover.setEnabled(false);
        txtQtdeVendida.setEnabled(false);
        ftxDataPedido.setEnabled(false);
        cbxFormaPagto.setEnabled(false);
        ftxCpfCliente.setEnabled(false);
        ftxCpfVendedor.setEnabled(false);
        btnCpfCliente.setEnabled(false);
        btnCpfVendedor.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        
       txtNumPedido.setEnabled(true);
       btnNumPedido.setEnabled(true);
                
        
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        txtCodProd.setEnabled(true);
        btnCodProd.setEnabled(true);
        tblItemPedido.setEnabled(true);
        btnRemover.setEnabled(true);
        txtQtdeVendida.setEnabled(true);
        ftxDataPedido.setEnabled(true);
        cbxFormaPagto.setEnabled(true);
        ftxCpfCliente.setEnabled(true);
        ftxCpfVendedor.setEnabled(true);
        btnCpfCliente.setEnabled(true);
        btnCpfVendedor.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnIncluir.setEnabled(true);
        
        alterar = true;
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ped.remove(pedenc);
        
        
        txtNumPedido.setEnabled(true);
        
        txtNumPedido.setText(null);
        ftxDataPedido.setText(null);
        cbxFormaPagto.setSelectedIndex(0);
        ftxCpfCliente.setText(null);
        lblNomeCliente.setText(" ");
        ftxCpfVendedor.setText(null);
        lblNomeVendedor.setText(" ");
        txtCodProd.setText(null);
        lblDescricao.setText(" ");
        txtQtdeVendida.setText(null);
        lblValTotal.setText(" ");
        lblQtdeItensPedidos.setText(" ");
        modTblPedido.setRowCount(0);
        
        btnNumPedido.setEnabled(true);
       
        
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        if(!txtNumPedido.getText().equals("")){
            ped.add(pedenc);
        }
        
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtNumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPedidoActionPerformed

    }//GEN-LAST:event_txtNumPedidoActionPerformed

    private void btnNumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumPedidoActionPerformed
        total = 0;
        
        DecimalFormat df = new DecimalFormat("#.##");
        
        if(ped.isEmpty()){
                    ftxDataPedido.setEnabled(true);
                    cbxFormaPagto.setEnabled(true);
                    ftxCpfCliente.setEnabled(true);

                    btnNumPedido.setEnabled(false);
                    btnCpfCliente.setEnabled(true);
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    
                    ftxDataPedido.setText(null);
                    cbxFormaPagto.setSelectedIndex(0);
                    ftxCpfCliente.setText(null);
                    lblNomeCliente.setText(" ");
                    ftxCpfVendedor.setText(null);
                    lblNomeVendedor.setText(" ");
                    txtCodProd.setText(null);
                    lblDescricao.setText(" ");
                    txtQtdeVendida.setText(null);
                    lblValTotal.setText(" ");
                    lblQtdeItensPedidos.setText(" ");
                    modTblPedido.setRowCount(0);
        }else{
            for (int i = 0; i < ped.size(); i++){

                if(ped.get(i).getNumero().equals(txtNumPedido.getText())){
                    System.out.println("Entrou no if " + txtNumPedido.getText());

                    pedenc = ped.get(i);

                    ftxDataPedido.setText(pedenc.getDataEmissao());
                    if(pedenc.getFormaPagto()){
                        cbxFormaPagto.setSelectedIndex(0);
                    }else{
                        cbxFormaPagto.setSelectedIndex(1);
                    }
                    
                    ftxCpfCliente.setText(pedenc.getCliente().getCpf());
                    lblNomeCliente.setText(pedenc.getCliente().getNome());
                    ftxCpfVendedor.setText(pedenc.getVendedor().getCpf());
                    lblNomeVendedor.setText(pedenc.getVendedor().getNome());

                    for(int j = 0; j < pedenc.getItensPedido().size(); j++){

                        subtotal = pedenc.getItensPedido().get(j).getQtdeVendida() * pedenc.getItensPedido().get(j).getProduto().getPreco();

                        String linha[] = {pedenc.getItensPedido().get(j).getProduto().getCodigo(),
                        pedenc.getItensPedido().get(j).getProduto().getDescricao(),
                        String.valueOf(pedenc.getItensPedido().get(j).getProduto().getPreco()),
                        String.valueOf(pedenc.getItensPedido().get(j).getQtdeVendida()), df.format(subtotal)};


                        modTblPedido.addRow(linha);

                        total += subtotal;

                        lblValTotal.setText(String.valueOf(total));
                        lblQtdeItensPedidos.setText(String.valueOf(modTblPedido.getRowCount()));

                    }

                    ftxDataPedido.setEnabled(false);
                    cbxFormaPagto.setEnabled(false);
                    ftxCpfCliente.setEnabled(false);
                    ftxCpfVendedor.setEnabled(false);
                    txtQtdeVendida.setEnabled(true);

                    btnCpfCliente.setEnabled(false);
                    btnCpfVendedor.setEnabled(false);
                    txtQtdeVendida.setEnabled(false);
                    tblItemPedido.setEnabled(false);
                    btnAlterar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                    break;
                }else{
                    ftxDataPedido.setEnabled(true);
                    cbxFormaPagto.setEnabled(true);
                    ftxCpfCliente.setEnabled(true);

                    btnNumPedido.setEnabled(false);
                    btnCpfCliente.setEnabled(true);
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    
                    ftxDataPedido.setText(null);
                    cbxFormaPagto.setSelectedIndex(0);
                    ftxCpfCliente.setText(null);
                    lblNomeCliente.setText(" ");
                    ftxCpfVendedor.setText(null);
                    lblNomeVendedor.setText(" ");
                    txtCodProd.setText(null);
                    lblDescricao.setText(" ");
                    txtQtdeVendida.setText(null);
                    lblValTotal.setText(" ");
                    lblQtdeItensPedidos.setText(" ");
                    modTblPedido.setRowCount(0);
                }
            }
        }
    }//GEN-LAST:event_btnNumPedidoActionPerformed

    private void btnCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpfClienteActionPerformed
        pedenc = new Pedido(txtNumPedido.getText(), ftxDataPedido.getText().replaceAll("/", ""));
        if(cbxFormaPagto.getSelectedIndex() == 0){
            pedenc.setFormaPagto(true);
        }else{
            pedenc.setFormaPagto(false);
        }
        clienc = null;

        for (int i = 0; i < pes.size(); i++){
            if(pes.get(i).getCpf().equals(ftxCpfCliente.getText().replaceAll("[\\.\\-]", ""))){
                clienc = (Cliente) pes.get(i);
                
                pedenc.setCliente((Cliente) clienc);
                
                lblNomeCliente.setText(clienc.getNome());

                ftxDataPedido.setEnabled(false);
                cbxFormaPagto.setEnabled(false);
                ftxCpfCliente.setEnabled(false);
                btnCpfCliente.setEnabled(false);
                ftxCpfVendedor.setEnabled(true);
                btnCpfVendedor.setEnabled(true);
            }
        }
        
        if(clienc == null){
            JOptionPane.showMessageDialog(null, "A pessoa procurada não é um cliente", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCpfClienteActionPerformed

    private void btnCpfVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpfVendedorActionPerformed
        vdenc = null;

        for (int i = 0; i < pes.size(); i++){
            if(pes.get(i).getCpf().equals(ftxCpfVendedor.getText().replaceAll("[\\.\\-]", ""))){
                vdenc = (Vendedor) pes.get(i);
                
                pedenc.setVendedor((Vendedor) vdenc);
                
                lblNomeVendedor.setText(vdenc.getNome());

                ftxCpfVendedor.setEnabled(false);
                btnCpfVendedor.setEnabled(false);
                txtCodProd.setEnabled(true);
                btnCodProd.setEnabled(true);
            }
        }
        
        if(vdenc == null){
            JOptionPane.showMessageDialog(null, "A pessoa procurada não é um cliente", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCpfVendedorActionPerformed

    private void btnCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodProdActionPerformed
        prdenc = null;
        
        for (int i = 0; i < prod.size(); i++){
            if(prod.get(i).getCodigo().equals(txtCodProd.getText())){
                prdenc = prod.get(i);
                
                lblDescricao.setText(prdenc.getDescricao());
                
                txtQtdeVendida.setEnabled(true);
                btnAdicionar.setEnabled(true);
                btnRemover.setEnabled(true);
            }
        }
        
        if(prdenc == null){
            JOptionPane.showMessageDialog(null, "Codigo de produto não existe", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCodProdActionPerformed

    private void txtCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCodProd;
    private javax.swing.JButton btnCpfCliente;
    private javax.swing.JButton btnCpfVendedor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNumPedido;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxFormaPagto;
    private javax.swing.JFormattedTextField ftxCpfCliente;
    private javax.swing.JFormattedTextField ftxCpfVendedor;
    private javax.swing.JFormattedTextField ftxDataPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JLabel lblQtdeItensPedidos;
    private javax.swing.JLabel lblValTotal;
    private javax.swing.JPanel pnDadosClientes;
    private javax.swing.JPanel pnDadosVendedor;
    private javax.swing.JPanel pnItensPedido;
    private javax.swing.JPanel pnPeido;
    private javax.swing.JTable tblItemPedido;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtQtdeVendida;
    // End of variables declaration//GEN-END:variables
    private final ArrayList <Produto> prod;
    private final ArrayList <Pedido> ped;
    private final ArrayList <Pessoa> pes;
    private Pedido pedenc;
    private Cliente clienc;
    private Vendedor vdenc;
    private Produto prdenc;
    private final DefaultTableModel modTblPedido;
    private double total = 0;
    private double subtotal = 0;
    private Pedido objPedido;
    private ItemPedido objItemPedido;
    private Produto prodselect;
    private boolean alterar = false;
}
